const module1 = require('../common-node/modules/1')
const module2 = require('../common-node/modules/2')
const module3 = require('../common-node/modules/3')
module1.foo()
module2()
module3.three()
module3.four()